// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEIxwHYrxPc10MtP2KqgFMTI0mgLpSmgs',
    appId: '1:446238065578:web:4e24e297361f111d6121d3',
    messagingSenderId: '446238065578',
    projectId: 'lets-meet-d2b3f',
    authDomain: 'lets-meet-d2b3f.firebaseapp.com',
    storageBucket: 'lets-meet-d2b3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnknqj0jqFEjStFJ3UGUyWfIZo08LOaO8',
    appId: '1:446238065578:android:23db2be5c7a9bd896121d3',
    messagingSenderId: '446238065578',
    projectId: 'lets-meet-d2b3f',
    storageBucket: 'lets-meet-d2b3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjIrHxbRXS3ckUs3xiDr_xcN2d5cxrcOU',
    appId: '1:446238065578:ios:9076892ef7bba8136121d3',
    messagingSenderId: '446238065578',
    projectId: 'lets-meet-d2b3f',
    storageBucket: 'lets-meet-d2b3f.appspot.com',
    iosClientId: '446238065578-hthasattjg7pum61crn7elm3gtaek4bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsMeetApp',
  );
}
